stages:
  - security

security-secrets:
  stage: security
  allow_failure: false
  image: alpine:3.24.2@sha256:294b683cb724975bec92580e1e685676bd4b50bda910ddb8c51d4cabeaec77e6
  variables:
    SCAN_PATH: "." 
  before_script:
    - apk add --no-cache git curl jq
    - curl -sSfL https://raw.githubusercontent.com/trufflesecurity/trufflehog/main/scripts/install.sh | sh -s -- -b /usr/local/bin
  script:
    - trufflehog filesystem "$SCAN_PATH" --results=verified,unknown --fail --json | jq
#  rules:
#    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
