---
apiVersion: v1
kind: Service
metadata:
  name: tblflp-
  namespace: minecraft
  labels:
    app: tblflp-
  annotations:
    metallb.universe.tf/address-pool: public
    metallb.universe.tf/allow-shared-ip: shared
    external-dns.alpha.kubernetes.io/hostname: mc.example.com
spec:
  type: LoadBalancer
  loadBalancerIP: 127.0.0.1
  externalTrafficPolicy: Local
  publishNotReadyAddresses: true
  ports:
  - name: minecraft
    port: 25565
    targetPort: 25565
    protocol: TCP
  selector:
    app: minecraft
    mcname: tblflp-
---
apiVersion: v1
kind: Service
metadata:
  name: tblflp-udp-
  namespace: minecraft
  labels:
    app: tblflp-udp-
  annotations:
    metallb.universe.tf/address-pool: public
    metallb.universe.tf/allow-shared-ip: shared
spec:
  type: LoadBalancer
  loadBalancerIP: 127.0.0.1
  externalTrafficPolicy: Local
  ports:
  - name: mcquery
    port: 25565
    targetPort: 25565
    protocol: UDP
  selector:
    app: minecraft
    mcname: tblflp-
