apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: karakeep

configMapGenerator:
  - envs:
    - env
    name: karakeep-configuration
    behavior: replace

generatorOptions:
  disableNameSuffixHash: true

resources:
  - https://github.com/SnoFox/karakeep//kubernetes?ref=v0.27.2
  - ingress.yaml
  - secrets.yaml

patches:
  - patch: |-
      - op: replace
        path: /spec/storageClassName
        value: freenas-iscsi-csi
    target:
      kind: PersistentVolumeClaim
  - patch: |-
      - op: replace
        path: /spec/type
        value: LoadBalancer
    target:
      kind: Service
      name: web
  - patch: |-
      $patch: delete
      apiVersion: v1
      kind: Secret
      metadata:
        name: karakeep-secrets
        namespace: karakeep

