apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: meilisearch-pvc
spec:
  storageClassName: "freenas-iscsi-csi"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
