---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: node-stage-secret-freenas-iscsi-csi-freenas-iscsi-democratic-cs
  namespace: democratic-csi
spec:
  itemPath: "vaults/FMT/items/democratic-csi:sc-iscsi-secret"
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: driver-secrets
  namespace: democratic-csi
spec:
  itemPath: "vaults/FMT/items/democratic-csi:driver-token"
