apiVersion: apiextensions.crossplane.io/v1alpha1
kind: ManagedResourceActivationPolicy
metadata:
  name: modern-only
spec:
  activate:
    - "*.iam.aws.m.upbound.io"
    - "*.dynamodb.aws.m.upbound.io"
