---
apiVersion: aws.m.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: tblflp-aws
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane
      name: aws-secrets
      key: credentials-file
