---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: upbound-provider-aws-dynamodb
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  package: xpkg.crossplane.io/crossplane-contrib/provider-aws-dynamodb:v2.8.1@sha256:96aca01adfbdefa8a2c1c0c102e92d934516a00717a2620d0fafd078d614d6d1
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: upbound-provider-aws-iam
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  package: xpkg.crossplane.io/crossplane-contrib/provider-aws-iam:v2.8.1@sha256:3f67b88214a228269bd69c6d2bfe9135e375035fa1b208221ceff80d016ab867
