---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: upbound-provider-aws-dynamodb
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  package: xpkg.crossplane.io/crossplane-contrib/provider-aws-dynamodb:v2.5.0@sha256:cf2c8ad6a36e5804308ca85bae89c9b6298861799d8691b5307919a2c960da26
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: upbound-provider-aws-iam
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  package: xpkg.crossplane.io/crossplane-contrib/provider-aws-iam:v2.5.0@sha256:3533f2193b0a9e72c5d6f5d3573554a5668f459c82ee8995084b277c6952fe29
