---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: upbound-provider-aws-dynamodb
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  package: xpkg.crossplane.io/crossplane-contrib/provider-aws-dynamodb:v2.9.0@sha256:ae03bce48f25bd2980a46d2d94239b2f8ae0441bf2d27be9613f7e156489ba6b
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: upbound-provider-aws-iam
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  package: xpkg.crossplane.io/crossplane-contrib/provider-aws-iam:v2.9.0@sha256:7b10066a13b381930abfcf7ac289f985cb651603bc28751f401c633c46e6b6af
