---
apiVersion: aws.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: tbflp-aws
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane
      name: aws-secrets
      key: credentials-file
