---
apiVersion: iam.aws.upbound.io/v1beta1
kind: Policy
metadata:
  name: external-dns-dynamodb-policy
spec:
  forProvider:
    description: Allow external-dns to read/write to its DynamoDB registry table
    policy: |
      {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Effect": "Allow",
            "Action": [
              "DynamoDB:DescribeTable",
              "DynamoDB:PartiQLDelete",
              "DynamoDB:PartiQLInsert",
              "DynamoDB:PartiQLUpdate",
              "DynamoDB:Scan"
            ],
            "Resource": [
              "arn:aws:dynamodb:us-west-2:*:table/external-dns"
            ]
          }
        ]
      }
    tags:
      Name: external-dns-dynamodb-policy
      ManagedBy: crossplane
      Purpose: external-dns-registry
  providerConfigRef:
    name: tblflp-aws
---
apiVersion: iam.aws.upbound.io/v1beta1
kind: RolePolicyAttachment
metadata:
  name: external-dns-dynamodb-attachment
spec:
  forProvider:
    policyArnRef:
      name: external-dns-dynamodb-policy
    role: Tableflippers-K8s # TODO: Get this role managed by Crossplane
  providerConfigRef:
    name: tblflp-aws
