---
apiVersion: iam.aws.m.upbound.io/v1beta1
kind: Policy
metadata:
  name: external-dns-dynamodb-policy
  namespace: external-dns
spec:
  forProvider:
    description: Allow external-dns to read/write to its DynamoDB registry table
    policy: |
      {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Effect": "Allow",
            "Action": [
              "DynamoDB:DescribeTable",
              "DynamoDB:PartiQLDelete",
              "DynamoDB:PartiQLInsert",
              "DynamoDB:PartiQLUpdate",
              "DynamoDB:Scan"
            ],
            "Resource": [
              "arn:aws:dynamodb:us-west-2:*:table/external-dns"
            ]
          }
        ]
      }
    tags:
      Name: external-dns-dynamodb-policy
      ManagedBy: crossplane
      Purpose: external-dns registry
  providerConfigRef:
    name: tblflp-aws
    kind: ClusterProviderConfig
---
apiVersion: iam.aws.m.upbound.io/v1beta1
kind: User
metadata:
  name: fmt-external-dns
  namespace: external-dns
spec:
  forProvider:
    tags:
      Name: fmt-external-dns
      ManagedBy: crossplane
      Purpose: external-dns registry
  providerConfigRef:
    name: tblflp-aws
    kind: ClusterProviderConfig
---
apiVersion: iam.aws.m.upbound.io/v1beta1
kind: AccessKey
metadata:
  name: fmt-external-dns-creds
  namespace: external-dns
spec:
  forProvider:
    userRef:
      name: fmt-external-dns
      namespace: external-dns
  writeConnectionSecretToRef:
    name: external-dns-secret
  providerConfigRef:
    name: tblflp-aws
    kind: ClusterProviderConfig
---
apiVersion: iam.aws.m.upbound.io/v1beta1
kind: UserPolicyAttachment
metadata:
  name: fmt-external-dns-dynamodb
  namespace: external-dns
spec:
  forProvider:
    policyArnRef:
      name: external-dns-dynamodb-policy
    userRef:
      name: fmt-external-dns
  providerConfigRef:
    name: tblflp-aws
    kind: ClusterProviderConfig
---
apiVersion: iam.aws.m.upbound.io/v1beta1
kind: UserPolicyAttachment
metadata:
  name: fmt-external-dns-r53
  namespace: external-dns
spec:
  forProvider:
    policyArn:
      name: arn:aws:iam::aws:policy/AmazonRoute53FullAccess
    userRef:
      name: fmt-external-dns
  providerConfigRef:
    name: tblflp-aws
    kind: ClusterProviderConfig
