---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cdio
  namespace: cdio
  annotations:
  labels:
    app: cdio
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: cdio
  serviceName: cdio
  template:
    metadata:
      labels:
        app: cdio
    spec:
      containers:
      - name: cdio
        image: dgtlmoon/changedetection.io:0.50.23@sha256:251cc90a138a67a91a1413a8948c039d74a622353174bb13078c6183a24b8d80
        imagePullPolicy: IfNotPresent
        env:
        - name: PLAYWRIGHT_DRIVER_URL
          value: ws://sockpuppet:3000
        - name: BASE_URL
          value: https://cdio.snow-galaxy.ts.net
        - name: TZ
          value: America/Los_Angeles
        resources: {}
        volumeMounts:
        - mountPath: /datastore
          name: data
      - name: sockpuppet
        image: dgtlmoon/sockpuppetbrowser:latest@sha256:9f2df6791a4cd9b2c3138cb62b5a8de7f27953cab84729fe09d28cbd341a8973
        imagePullPolicy: Always
        env:
        - name: SCREEN_WIDTH
          value: "1920"
        - name: SCREEN_HEIGHT
          value: "1024"
        - name: SCREEN_DEPTH
          value: "16"
        - name: MAX_CONCURRENT_CHROME_PROCESSES
          value: "20"
        securityContext:
          capabilities:
            add: ["CAP_SYS_RESOURCE"]
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: "freenas-iscsi-csi"
        resources:
          requests:
            storage: 20Gi
