---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cdio
  namespace: cdio
  annotations:
  labels:
    app: cdio
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: cdio
  serviceName: cdio
  template:
    metadata:
      labels:
        app: cdio
    spec:
      containers:
      - name: cdio
        image: dgtlmoon/changedetection.io:0.60.4@sha256:7bb6963b730df6a1070f7a08a607b0eb7a87fe65abfa4742d876ad33bb1267eb
        imagePullPolicy: IfNotPresent
        env:
        - name: PLAYWRIGHT_DRIVER_URL
          value: ws://sockpuppet:3000
        - name: BASE_URL
          value: https://cdio.snow-galaxy.ts.net
        - name: TZ
          value: America/Los_Angeles
        resources: {}
        volumeMounts:
        - mountPath: /datastore
          name: data
      - name: sockpuppet
        image: dgtlmoon/sockpuppetbrowser:latest@sha256:1d8f72d2ce2085faed4232e5ae1e65c02efe5b831a18e127829b267c260b4fb2
        imagePullPolicy: Always
        env:
        - name: SCREEN_WIDTH
          value: "1920"
        - name: SCREEN_HEIGHT
          value: "1024"
        - name: SCREEN_DEPTH
          value: "16"
        - name: MAX_CONCURRENT_CHROME_PROCESSES
          value: "20"
        securityContext:
          capabilities:
            add: ["CAP_SYS_RESOURCE"]
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: "freenas-iscsi-csi"
        resources:
          requests:
            storage: 20Gi
