apiVersion: v1
kind: Service
metadata:
  name: thelounge
  namespace: irc
  labels:
    app: thelounge
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 9000
    name: thelounge
  selector:
    app: thelounge
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: thelounge
  namespace: irc
spec:
  selector:
    matchLabels:
      app: thelounge
  serviceName: thelounge
  replicas: 1
  template:
    metadata:
      labels:
        app: thelounge
    spec:
      nodeName: holo.snofox.net
      containers:
      - name: thelounge
        imagePullPolicy: Always
        image: ghcr.io/thelounge/thelounge:4.4.3@sha256:c2aa0916203b298ffaf3a36c4eb60ef73c1006448d430e218d37840472e84e50
        resources:
          requests:
            memory: "2Gi"
            cpu: "500m"
        ports:
        - containerPort: 9000
          name: thelounge
        env:
        - name: TZ
          value: "America/Los_Angeles"
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        volumeMounts:
        - name: configdir
          mountPath: /var/opt/thelounge
  volumeClaimTemplates:
    - metadata:
        name: configdir
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: "freenas-iscsi-csi"
        resources:
          requests:
            storage: 100Gi
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: irc
  name: thelounge-ts
  annotations: {}
spec:
  ingressClassName: tailscale
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: thelounge
            port:
              number: 80
  tls:
  - hosts:
    - lounge
