apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: onepassword
  labels:
    snofox.net/catagory: system
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: onepassword
  sources:
    - repoURL: https://1password.github.io/connect-helm-charts/
      chart: connect
      targetRevision: 2.2.0
      helm:
        valueFiles:
        - $values/values/1password.yml
    - repoURL: https://gitlab.com/SnoFox/kubernetes.git
      targetRevision: master
      ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
