apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: external-dns
  labels:
    snofox.net/catagory: system
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: external-dns
  sources:
    - repoURL: https://gitlab.com/SnoFox/kubernetes.git
      path: apps/external-dns
      targetRevision: master
    - repoURL: https://kubernetes-sigs.github.io/external-dns/
      chart: external-dns
      targetRevision: 1.20.0
      helm:
        valueFiles:
        - $values/values/external-dns.yaml
    - repoURL: https://gitlab.com/SnoFox/kubernetes.git
      targetRevision: master
      ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
