apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: argocd
  labels:
    snofox.net/catagory: system
spec:
  project: default
  sources:
    - repoURL: https://gitlab.com/SnoFox/kubernetes.git
      path: apps/metallb
      targetRevision: HEAD
    - repoURL: https://gitlab.com/SnoFox/k8s.git
      path: apps/metallb
      targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: metallb-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
