tableflip:
  factorio: {}
factorio-server-charts:
  serverPassword:
    passwordSecret: server-secret
  rcon:
    passwordSecret: rcon-secret
    serviceAnnotations:
      metallb.universe.tf/address-pool: public
      metallb.universe.tf/allow-shared-ip: shared
      external-dns.alpha.kubernetes.io/hostname: rcon.factorio.tableflip.zone
  service:
    annotations:
      metallb.universe.tf/address-pool: public
      metallb.universe.tf/allow-shared-ip: shared
      external-dns.alpha.kubernetes.io/hostname: factorio.tableflip.zone
  persistence:
    storageClassName: freenas-iscsi-csi
  ## @param server_settings.require_user_verification When set to true, the server will only allow clients that have a valid Factorio.com account
  ## @param server_settings.max_upload_in_kilobytes_per_second Optional, default value is 0. 0 means unlimited
  ## @param server_settings.max_upload_slots Optional, default value is 5. 0 means unlimited
  ## @param server_settings.minimum_latency_in_ticks Optional, one tick is 16ms in default speed, default value is 0. 0 means no minimum
  ## @param server_settings.ignore_player_limit_for_returning_players Players that played on this map already can join even when the max player limit is reached
  ## @param server_settings.allow_commands Possible values are true, false and admins-only
  ## @param server_settings.autosave_interval Autosave interval in minutes
  ## @param server_settings.autosave_slots Server autosave slots, it is cycled through when the server autosaves
  ## @param server_settings.afk_autokick_interval How many minutes must pass before someone is kicked when doing nothing, 0 for never
  ## @param server_settings.auto_pause Whether the server should be paused when no players are present
  ## @param server_settings.auto_pause_when_players_connect Whether should the server be paused when someone is connecting to the server.
  ## @param server_settings.only_admins_can_pause_the_game Specifies if anyone can pause or only admins
  ## @param server_settings.autosave_only_on_server Whether autosaves should be performed only on the server or also on all connected clients. Default is true
  ## @param server_settings.non_blocking_saving Highly experimental feature, enable only at your own risk
  ## @param server_settings.max_heartbeats_per_second Network tick rate. Maximum rate game updates packets are sent at before bundling them together. Minimum value is 6, maximum value is 240.
  ## @param server_settings.minimum_segment_size Minimum network messages segment size
  ## @param server_settings.minimum_segment_size_peer_count Minimum network messages segment count
  ## @param server_settings.maximum_segment_size Maximum network messages segment size
  ## @param server_settings.maximum_segment_size_peer_count Minimum network messages segment count
  server_settings:
    name: Factorio Bros
    description: "Factorio running on Kubernetes"
    tags: []
    max_players: 0
    visibility:
      public: false
      lan: false
    auto_pause: true
