apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: argocd
  labels:
    snofox.net/catagory: system
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  source:
    repoURL: https://gitlab.com/SnoFox/kubernetes.git
    path: apps/argocd
    targetRevision: HEAD
  syncPolicy:
    automated:
      enable: false
      prune: false
      selfHeal: false
    syncOptions:
    - CreateNamespace=true
