apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: ingress-nginx
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-nginx
  sources:
    - repoURL: https://kubernetes.github.io/ingress-nginx
      # https://github.com/kubernetes/ingress-nginx?tab=readme-ov-file#supported-versions-table
      chart: ingress-nginx
      targetRevision: 4.12.2
    #  helm:
    #    valueFiles:
    #    - $values/apps/ingress-nginx/values.yml
    #- repoURL: https://gitlab.com/SnoFox/kubernetes.git
    #  targetRevision: master
    #  ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
