apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: recipes-media
  namespace: tandoor
  labels:
    app: recipes
spec:
  storageClassName: "freenas-iscsi-csi"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: recipes-static
  namespace: tandoor
  labels:
    app: recipes
spec:
  storageClassName: "freenas-iscsi-csi"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
