apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-cm
  namespace: argocd
data:
#  application.instanceLabelKey: argocd.argoproj.io/instance
  #resource.ignoreResourceUpdatesEnabled: "true"
  #resource.customizations.ignoreResourceUpdates.apps_Deployment: |
  resource.customizations.ignoreDifferences.apps_Deployment: |
    jqPathExpressions:
    - '.spec.template.metadata.annotations["operator.1password.io/last-restarted"]'
    - '.spec.template.metadata.annotations["kubectl.kubernetes.io/restartedAt"]'
  resource.customizations.ignoreDifferences.Service: |
    jqPathExpressions:
    - 'select(.metadata.annotations."tailscale.com/tailnet-ip" != null or .metadata.annotations."tailscale.com/tailnet-fqdn" != null) | .spec.externalName'
  resource.exclusions: |
    - apiGroups:
      - "*"
      kinds:
      - "Secret"
      clusters:
      - "*"
